version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      # Note: With the non-root user in the Dockerfile, we need to ensure proper permissions
      # The source code is now mounted as read-only to avoid permission issues
      - ./backend:/app:ro
      # Create a volume for the .venv to persist between container restarts
      # This avoids rebuilding the virtual environment each time
      - backend-venv:/app/.venv
    user: appuser
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  backend-venv:
    # Named volume for the virtual environment
